### ISSUE TITLE
Aggragate error

### ISSUE THREAD

**Issue by UjjualUSspericorn** [XeroAPI/node-oauth2-example#4]
I have used the scopes and credentials that works on postman,But here it is throwing below given error. Any idea on this ?

(node:9983) UnhandledPromiseRejectionWarning: AggregateError: 
    RequestError: Request timed out
        at timeoutFn (/opt/lampp/htdocs/2Stay/XERO/node-oauth2-example/node_modules/got/index.js:333:53)
        at asPromise (/opt/lampp/htdocs/2Stay/XERO/node-oauth2-example/node_modules/got/index.js:411:18)

**Comment by UjjualUSspericorn** [comment]
Since no one's around I used there API's .!

**Comment by SerKnight** [comment]
@UjjualUSspericorn - we are refactoring the project to use GOT (a new http library) but not sure how you got on the branch with that code. Are you using the npm package?

**Comment by UjjualUSspericorn** [comment]
Hi, @SerKnight 

Here I just cloned this repo and replaced the credentials on config.json with mine. 
But in another attempt I tried xero-node seperately and It also throwed the same error.Please see the below URL.
 

https://github.com/XeroAPI/xero-node/issues/485
[xero-node](https://github.com/XeroAPI/xero-node/issues/485)
